apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Bharaths73/Chat-App-K8s.git'
    targetRevision: HEAD
    path: k8s/Frontend
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: chat-app-namespace
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
