apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Bharaths73/Chat-App-K8s.git'
    targetRevision: k8s-testing
    path: k8s/Kafka
    helm:
      valueFiles:
        - values.yaml
      chart: kafka
      repoURL: https://charts.bitnami.com/bitnami
      version: 17.0.1
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kafka
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
