apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: kafka
      targetRevision: 32.4.3
      helm:
        valueFiles:
          - $values/k8s/Kafka/values.yaml
    - repoURL: 'https://github.com/Bharaths73/Chat-App-K8s.git'
      targetRevision: HEAD
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kafka
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
