apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: redis
      targetRevision: 22.0.7
    - repoURL: 'https://github.com/Bharaths73/Chat-App-K8s.git'
      targetRevision: k8s-testing
      ref: values
  source:
    helm:
      valueFiles:
        - $values/k8s/Redis/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: redis
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
